CREATE GLOBAL TEMPORARY TABLE TEMP_IDS (
  ID NUMBER
) ON COMMIT PRESERVE ROWS;

-- Report Results

TRUNCATE TABLE RPT_RESULT;

DELETE FROM RPT_RESULT_DATA;

-- Executed Configurations

TRUNCATE TABLE TEMP_IDS;

INSERT INTO TEMP_IDS (ID) (
  SELECT vp2.PARAM_ID
  FROM VALUES_PARAMS vp2
  WHERE EXISTS(
      SELECT vp.*
      FROM EX_STATUS es
        INNER JOIN EX_RCONFIG ec
          ON ec.ID = es.EXCONFIG_ID
        INNER JOIN EX_TEMPLT_QUERY etq
          ON etq.EX_RCONFIG_ID = ec.ID
        LEFT JOIN EX_TEMPLT_QRS_EX_QUERY_VALUES etqeqv
          ON etqeqv.EX_TEMPLT_QUERY_ID = etq.ID
        LEFT JOIN VALUE v
          ON v.ID = etqeqv.EX_QUERY_VALUE_ID
        LEFT JOIN VALUES_PARAMS vp
          ON vp.VALUE_ID = v.ID
      WHERE vp.VALUE_ID = vp2.VALUE_ID
  )
);

DELETE FROM VALUES_PARAMS vp
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE vp.PARAM_ID = t.ID
);

DELETE FROM EX_QUERY_EXP eqe
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE eqe.ID = t.ID
);

DELETE FROM QUERY_EXP_VALUE qev
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE qev.ID = t.ID
);

DELETE FROM EX_SQL_VALUE esv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE esv.ID = t.ID
);

DELETE FROM SQL_VALUE sv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE sv.ID = t.ID
);

DELETE FROM SQL_TEMPLT_VALUE stv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE stv.ID = t.ID
);

DELETE FROM PARAM p
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE p.ID = t.ID
);

TRUNCATE TABLE TEMP_IDS;

INSERT INTO TEMP_IDS (ID) (
  SELECT vp2.PARAM_ID
  FROM VALUES_PARAMS vp2
  WHERE EXISTS(
      SELECT vp.*
      FROM EX_STATUS es
        INNER JOIN EX_RCONFIG ec
          ON ec.ID = es.EXCONFIG_ID
        INNER JOIN EX_TEMPLT_QUERY etq
          ON etq.EX_RCONFIG_ID = ec.ID
        LEFT JOIN EX_TEMPLT_QRS_EX_TEMPLT_VALUES etqetv
          ON etqetv.EX_TEMPLT_QUERY_ID = etq.ID
        LEFT JOIN VALUE v
          ON v.ID = etqetv.EX_TEMPLT_VALUE_ID
        LEFT JOIN VALUES_PARAMS vp
          ON vp.VALUE_ID = v.ID
      WHERE vp.VALUE_ID = vp2.VALUE_ID
  )
);

DELETE FROM VALUES_PARAMS vp
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE vp.PARAM_ID = t.ID
);

DELETE FROM EX_QUERY_EXP eqe
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE eqe.ID = t.ID
);

DELETE FROM QUERY_EXP_VALUE qev
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE qev.ID = t.ID
);

DELETE FROM EX_SQL_VALUE esv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE esv.ID = t.ID
);

DELETE FROM SQL_VALUE sv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE sv.ID = t.ID
);

DELETE FROM SQL_TEMPLT_VALUE stv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE stv.ID = t.ID
);

DELETE FROM PARAM p
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE p.ID = t.ID
);

TRUNCATE TABLE TEMP_IDS;

INSERT INTO TEMP_IDS (ID) (
  SELECT v2.ID
  FROM VALUE v2
  WHERE EXISTS(
      SELECT vp.*
      FROM EX_STATUS es
        INNER JOIN EX_RCONFIG ec
          ON ec.ID = es.EXCONFIG_ID
        INNER JOIN EX_TEMPLT_QUERY etq
          ON etq.EX_RCONFIG_ID = ec.ID
        LEFT JOIN EX_TEMPLT_QRS_EX_QUERY_VALUES etqeqv
          ON etqeqv.EX_TEMPLT_QUERY_ID = etq.ID
        LEFT JOIN VALUE v
          ON v.ID = etqeqv.EX_QUERY_VALUE_ID
      WHERE v.ID = v2.ID
  )
);

DELETE FROM EX_TEMPLT_QRS_EX_QUERY_VALUES etqeqv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE etqeqv.EX_QUERY_VALUE_ID = t.ID
);

DELETE FROM EX_QUERY_VALUE eqv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE eqv.ID = t.ID
);

DELETE FROM QUERY_VALUE qv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE qv.ID = t.ID
);

DELETE FROM VALUE v
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE v.ID = t.ID
);

TRUNCATE TABLE TEMP_IDS;

INSERT INTO TEMP_IDS (ID) (
  SELECT v2.ID
  FROM VALUE v2
  WHERE EXISTS(
      SELECT vp.*
      FROM EX_STATUS es
        INNER JOIN EX_RCONFIG ec
          ON ec.ID = es.EXCONFIG_ID
        INNER JOIN EX_TEMPLT_QUERY etq
          ON etq.EX_RCONFIG_ID = ec.ID
        LEFT JOIN EX_TEMPLT_QRS_EX_TEMPLT_VALUES etqetv
          ON etqetv.EX_TEMPLT_QUERY_ID = etq.ID
        LEFT JOIN VALUE v
          ON v.ID = etqetv.EX_TEMPLT_VALUE_ID
      WHERE v.ID = v2.ID
  )
);

DELETE FROM EX_TEMPLT_QRS_EX_TEMPLT_VALUES etqetv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE etqetv.EX_TEMPLT_VALUE_ID = t.ID
);

DELETE FROM EX_TEMPLT_VALUE etv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE etv.ID = t.ID
);

DELETE FROM TEMPLT_VALUE tv
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE tv.ID = t.ID
);

DELETE FROM VALUE v
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE v.ID = t.ID
);

TRUNCATE TABLE TEMP_IDS;

INSERT INTO TEMP_IDS (ID) (
  SELECT etq2.EX_DATE_RANGE_INFO_ID
  FROM EX_TEMPLT_QUERY etq2
  WHERE EXISTS(
      SELECT etq.*
      FROM EX_STATUS es
        INNER JOIN EX_RCONFIG ec
          ON ec.ID = es.EXCONFIG_ID
        INNER JOIN EX_TEMPLT_QUERY etq
          ON etq.EX_RCONFIG_ID = ec.ID
      WHERE etq.ID = etq2.ID
  )
);

DELETE
FROM EX_TEMPLT_QUERY etq2
WHERE EXISTS(
    SELECT etq.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
      RIGHT JOIN EX_TEMPLT_QUERY etq
        ON etq.EX_RCONFIG_ID = ec.ID
);

DELETE FROM EX_DATE_RANGE edr
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE edr.ID = t.ID
);

DELETE
FROM SHARED_WITH sw2
WHERE EXISTS(
    SELECT sw.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
      LEFT JOIN SHARED_WITH sw
        ON sw.EX_RCONFIG_ID = ec.ID
    WHERE sw.ID = sw2.ID
);

DELETE
FROM EX_DELIVERIES_SHARED_WITHS edsw2
WHERE EXISTS(
    SELECT edsw.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
      LEFT JOIN EX_DELIVERY ed
        ON ec.EX_DELIVERY_ID = ed.ID
      LEFT JOIN EX_DELIVERIES_SHARED_WITHS edsw
        ON edsw.EX_DELIVERY_ID = ed.ID
    WHERE edsw.EX_DELIVERY_ID = edsw2.EX_DELIVERY_ID
);

DELETE
FROM EX_DELIVERIES_RPT_FORMATS edrf2
WHERE EXISTS(
    SELECT edrf.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
      LEFT JOIN EX_DELIVERY ed
        ON ec.EX_DELIVERY_ID = ed.ID
      LEFT JOIN EX_DELIVERIES_RPT_FORMATS edrf
        ON edrf.EX_DELIVERY_ID = ed.ID
    WHERE edrf.EX_DELIVERY_ID = edrf2.EX_DELIVERY_ID
);

DELETE
FROM EX_DELIVERIES_EMAIL_USERS edeu2
WHERE EXISTS(
    SELECT edeu.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
      LEFT JOIN EX_DELIVERY ed
        ON ec.EX_DELIVERY_ID = ed.ID
      LEFT JOIN EX_DELIVERIES_EMAIL_USERS edeu
        ON edeu.EX_DELIVERY_ID = ed.ID
    WHERE edeu.EX_DELIVERY_ID = edeu2.EX_DELIVERY_ID
);

TRUNCATE TABLE TEMP_IDS;

INSERT INTO TEMP_IDS (ID) (
  SELECT ed2.ID
  FROM EX_DELIVERY ed2
  WHERE EXISTS(
      SELECT ed.*
      FROM EX_STATUS es
        LEFT JOIN EX_STATUSES_RPT_FORMATS exsrf
          ON exsrf.EX_STATUS_ID = es.ID
        LEFT JOIN EX_STATUSES_SHARED_WITHS essw
          ON essw.EX_STATUS_ID = es.ID
        INNER JOIN EX_RCONFIG ec
          ON ec.ID = es.EXCONFIG_ID
        LEFT JOIN EX_DELIVERY ed
          ON ec.EX_DELIVERY_ID = ed.ID
      WHERE ed.ID = ed2.ID
  )
);

DELETE
FROM EX_RCONFIGS_TAGS ect2
WHERE EXISTS(
    SELECT ect.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
      LEFT JOIN EX_RCONFIGS_TAGS ect
        ON ect.EXC_RCONFIG_ID = ec.ID
    WHERE ect.EXC_RCONFIG_ID = ect2.EXC_RCONFIG_ID
);

DELETE
FROM EX_RCONFIG ec2
WHERE EXISTS(
    SELECT ec.*
    FROM EX_STATUS es
      INNER JOIN EX_RCONFIG ec
        ON ec.ID = es.EXCONFIG_ID
    WHERE ec.ID = ec2.ID
);

DELETE FROM EX_DELIVERY ed
WHERE EXISTS(
    SELECT t.*
    FROM TEMP_IDS t
    WHERE ed.ID = t.ID
);

DELETE
FROM EX_STATUSES_SHARED_WITHS essw2
WHERE EXISTS(
    SELECT essw.*
    FROM EX_STATUS es
      LEFT JOIN EX_STATUSES_SHARED_WITHS essw
        ON essw.EX_STATUS_ID = es.ID
    WHERE essw.EX_STATUS_ID = essw2.EX_STATUS_ID
);

DELETE
FROM EX_STATUSES_RPT_FORMATS exsrf2
WHERE EXISTS(
    SELECT exsrf.*
    FROM EX_STATUS es
      LEFT JOIN EX_STATUSES_RPT_FORMATS exsrf
        ON exsrf.EX_STATUS_ID = es.ID
    WHERE exsrf.EX_STATUS_ID = exsrf2.EX_STATUS_ID
);

DELETE
FROM EX_STATUS es2
WHERE EXISTS(
    SELECT es.*
    FROM EX_STATUS es
    WHERE es.ID = es2.ID
);

DELETE FROM NOTIFICATION;

TRUNCATE TABLE TEMP_IDS;

DROP TABLE TEMP_IDS;