databaseChangeLog = {
    changeSet(author: "Sargam (generated)", id: "201908050638-1") {
        sql("ALTER TABLE DELIVERY MODIFY ADDITIONAL_ATTACHMENTS VARCHAR2(32000)")
        sql("ALTER TABLE EX_DELIVERY MODIFY ADDITIONAL_ATTACHMENTS VARCHAR2(32000)")
    }
}