databaseChangeLog = {
    changeSet(author: "sachins", id: "041220202020-1001") {
        sql("UPDATE QUALITY_CASE_DATA SET WORKFLOW_STATE_ID = 14 WHERE WORKFLOW_STATE_ID IS NULL")
        sql("UPDATE QUALITY_SUBMISSION SET WORKFLOW_STATE_ID = 14 WHERE WORKFLOW_STATE_ID IS NULL")
        sql("UPDATE QUALITY_SAMPLING SET WORKFLOW_STATE_ID = 14 WHERE WORKFLOW_STATE_ID IS NULL")
    }
}