databaseChangeLog = {
    changeSet(author: "Siddharth", id: "20240906072540-7") {
        sql("""UPDATE EX_RCONFIG SET USED_CASE_SERIES_ID = NULL WHERE SIGNAL_CONFIGURATION = 1 AND USED_CASE_SERIES_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM EX_CASE_SERIES WHERE EX_CASE_SERIES.id = EX_RCONFIG.USED_CASE_SERIES_ID);""")
    }
}