package com.rxlogix.enums


public enum CommentTypeEnum {
    REPORT_RESULT, EXECUTED_CONFIGURATION,PUBLISHER_SECTION,PUBLISHER_FULL, CASE_QUALITY, SUBMISSION_QUALITY, SAMPLING,CASE_CORRECTIONS, DRILLDOWN_RECORD, SCHEDULER,SCHEDULER_RR
}
