package com.rxlogix.enums


enum ExecutingEntityTypeEnum {
    CONFIGURATION,
    NEW_EXECUTED_CONFIGURATION,
    EXECUTED_CONFIGURATION,
    PERIODIC_CONFIGURATION,
    EXECUTED_PERIODIC_CONFIGURATION,
    EXECUTED_PERIODIC_CONFIGURATION_FINAL,
    EXECUTED_PERIODIC_NEW_SECTION,
    EXECUTED_CONFIGURATION_NEW_SECTION,
    CASESERIES,
    EXCECUTED_CASESERIES,
    NEW_EXCECUTED_CASESERIES,
    EXECUTED_PERIODIC_CONFIGURATION_CASES_AND_FINAL,
    EXECUTED_PERIODIC_CONFIGURATION_CASES_AND_DRAFT,
    EXECUTED_PERIODIC_CONFIGURATION_REFRESH_CASES,
    ICSR_CONFIGURATION,
    EXECUTED_ICSR_CONFIGURATION,
    ICSR_PROFILE_CONFIGURATION,
    EXECUTED_ICSR_PROFILE_CONFIGURATION,
    ON_DEMAND_NEW_SECTION,
    ON_DEMAND_PERIODIC_NEW_SECTION,
    INBOUND_COMPLIANCE,
    EXECUTED_INBOUND_COMPLIANCE
}

