package com.rxlogix.enums

/**
 * Created by gologuzov on 14.12.16.
 */
enum WidgetTypeEnum {
    LAST_REPORTS,
    CHART,
    ACTION_ITEMS,
    CALENDAR,
    REPORT_REQUEST_SUMMARY,
    ACTION_ITEMS_SUMMARY,
    ADHOC_REPORTS_SUMMARY,
    AGGREGATE_REPORTS_SUMMARY,
    ETL,
    QUALITY_ACTION_ITEMS,
    QUALITY_ACTION_ITEMS_SUMMARY,
    QUALITY_CASE_COUNT,
    QUALITY_PRODUCT_COUNT,
    QUALITY_ENTRYSITE_COUNT,
    QUALITY_ERROR_COUNT,
    QUALITY_LATEST_ISSUES,
    QUALITY_CASE_REPORT_TYPE,
    ADVANCED_REPORT_REQUEST,
    CASE_COUNT_BY_ERROR,
    ACTION_PLAN_PVC,
    ACTION_PLAN_PVQ,
    SUBMISSION_COUNT_BY_ERROR,
    ADVANCED_PUBLISHER,
    COMPLIANCE_PUBLISHER,
    SPOTFIRE,
    ICSR_TRACKING,
    CONFIGURATIONS
}