name: Client Side Tools and Coverage

on:
  pull_request:
    branches:
      - main  # Only runs for PRs targeting the main branch


  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Send Client Side Tools and Coverage Results - 
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
         export CODACY_CODE=$GITHUB_WORKSPACE
          # sudo apt-get -qq update
          # sudo apt-get -y -qq install openjdk-8-jdk openjdk-8-jre
          # curl -s "https://get.sdkman.io" | bash
          # source "$HOME/.sdkman/bin/sdkman-init.sh"
          # sdk install gradle 7.3.3
          gradle -v
          REPO_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.head_ref }}"
          
          echo REPO_NAME
          curl -X POST -u "Ankit.Tiwari@rxlogix.com:11b28691899215ef23612c7e13ee239270" "https://pvbuild-eng.rxlogix.com/job/Jenkins-api_test/build"
          
          #./gradlew clean check jacocoTestReport
          # gradle jacocoTestReport
          
          #bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/reports/jacoco/test/jacocoTestReport.xml
         
